package de.konavigator.app.calculator

enum class TradeCalculationError {
    INVALID_PLANNED_ENTRY_PRICE,
    INVALID_TARGET_LEVERAGE,
    INVALID_RATIO,
    INVALID_DERIVED_KNOCKOUT_PRICE,
    INVALID_EXCHANGE_RATE,
    INVALID_THEORETICAL_PRODUCT_VALUE,
    INVALID_CALCULATED_LEVERAGE
}
