package de.konavigator.app.domain.dataquality

enum class DataQualitySeverity {
    WARNING,
    BLOCKING
}

enum class DataQualityComponent {
    PRODUCT_SPECIFICATION,
    PRODUCT_MARKET_DATA,
    CROSS_MODEL_COMPATIBILITY
}

enum class DataQualityCategory {
    MISSING_REQUIRED_DATA,
    INVALID_IDENTIFIER,
    INVALID_NUMERIC_VALUE,
    INVALID_CURRENCY,
    INVALID_RATIO,
    INVALID_QUOTE_RELATION,
    INCONSISTENT_IDENTIFIERS,
    INCONSISTENT_CURRENCIES,
    INCONSISTENT_TIMESTAMPS
}

enum class DataQualityFindingCode {
    SPECIFICATION_MISSING_PRODUCT_ISIN,
    SPECIFICATION_INVALID_PRODUCT_WKN,
    SPECIFICATION_MISSING_ISSUER_ID,
    SPECIFICATION_MISSING_UNDERLYING_ID,
    SPECIFICATION_INVALID_BASE_PRICE,
    SPECIFICATION_INVALID_KNOCKOUT_BARRIER,
    SPECIFICATION_INVALID_RATIO,
    SPECIFICATION_INVALID_UNDERLYING_CURRENCY,
    SPECIFICATION_INVALID_PRODUCT_CURRENCY,
    MARKET_DATA_MISSING_PRODUCT_ISIN,
    MARKET_DATA_MISSING_SOURCE_ID,
    MARKET_DATA_INVALID_CURRENCY,
    MARKET_DATA_INVALID_BID,
    MARKET_DATA_MISSING_BID_TIMESTAMP,
    MARKET_DATA_ORPHAN_BID_TIMESTAMP,
    MARKET_DATA_INVALID_ASK,
    MARKET_DATA_MISSING_ASK_TIMESTAMP,
    MARKET_DATA_ORPHAN_ASK_TIMESTAMP,
    MARKET_DATA_BID_ABOVE_ASK,
    COMPATIBILITY_PRODUCT_ISIN_MISMATCH,
    COMPATIBILITY_PRODUCT_CURRENCY_MISMATCH
}

data class DataQualityFinding(
    val category: DataQualityCategory,
    val severity: DataQualitySeverity,
    val code: DataQualityFindingCode,
    val component: DataQualityComponent
)
