package de.konavigator.app.application.productdiscovery

import de.konavigator.app.domain.availability.MarketDataCalculationAvailabilityError
import de.konavigator.app.domain.availability.MarketDataCalculationAvailabilityResult
import de.konavigator.app.domain.availability.MarketDataCalculationType
import de.konavigator.app.domain.calculator.MarketDataCalculationError
import de.konavigator.app.domain.calculator.MarketDataCalculationResult
import de.konavigator.app.domain.calculator.MarketDataCalculator
import de.konavigator.app.domain.dataquality.DataQualityAssessment
import de.konavigator.app.domain.dataquality.DataQualityCategory
import de.konavigator.app.domain.dataquality.DataQualityComponent
import de.konavigator.app.domain.dataquality.DataQualityFinding
import de.konavigator.app.domain.dataquality.DataQualityFindingCode
import de.konavigator.app.domain.dataquality.DataQualitySeverity
import de.konavigator.app.domain.freshness.MarketDataFreshnessError
import de.konavigator.app.domain.freshness.MarketDataFreshnessResult
import de.konavigator.app.domain.model.KnockoutProductMarketData
import de.konavigator.app.domain.model.KnockoutProductSpecification
import de.konavigator.app.domain.model.KnockoutProductSpecificationSnapshot
import de.konavigator.app.domain.model.TradeDirection
import de.konavigator.app.domain.orchestration.MarketDataCalculationValue
import de.konavigator.app.domain.source.MarketDataSourceError
import de.konavigator.app.domain.source.MarketDataSourceResult
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertSame
import org.junit.Assert.assertTrue
import org.junit.Test

class KnockoutProductCandidateCalculationApplicationServiceTest {
    private val service = KnockoutProductCandidateCalculationApplicationService()

    @Test fun purchasePriceUsesAsk() { val value=success(MarketDataCalculationType.PURCHASE_PRICE,candidate(bid=1.0,ask=2.5)) as MarketDataCalculationValue.PurchasePrice; assertEquals(2.5,value.value,0.0) }
    @Test fun purchasePricePreservesMarketDataCurrency() { val value=success(MarketDataCalculationType.PURCHASE_PRICE,candidate(currency="USD")) as MarketDataCalculationValue.PurchasePrice; assertEquals("USD",value.currency) }
    @Test fun salePriceUsesBid() { val value=success(MarketDataCalculationType.SALE_PRICE,candidate(bid=1.5,ask=9.0)) as MarketDataCalculationValue.SalePrice; assertEquals(1.5,value.value,0.0) }
    @Test fun salePricePreservesMarketDataCurrency() { val value=success(MarketDataCalculationType.SALE_PRICE,candidate(currency="CHF")) as MarketDataCalculationValue.SalePrice; assertEquals("CHF",value.currency) }
    @Test fun spreadCalculatesAbsoluteSpreadWithExistingCalculator() { val value=success(MarketDataCalculationType.SPREAD,candidate(bid=9.0,ask=10.0)) as MarketDataCalculationValue.Spread; assertEquals(1.0,value.absoluteSpread,0.0) }
    @Test fun spreadCalculatesRelativeSpreadToAskPercentWithExistingCalculator() { val value=success(MarketDataCalculationType.SPREAD,candidate(bid=9.0,ask=10.0)) as MarketDataCalculationValue.Spread; assertEquals(10.0,value.relativeSpreadToAskPercent,0.0) }
    @Test fun spreadPreservesMarketDataCurrency() { val value=success(MarketDataCalculationType.SPREAD,candidate(currency="GBP")) as MarketDataCalculationValue.Spread; assertEquals("GBP",value.currency) }
    @Test fun midCalculatesValueWithExistingCalculator() { val value=success(MarketDataCalculationType.MID,candidate(bid=8.0,ask=10.0)) as MarketDataCalculationValue.MidPrice; assertEquals(9.0,value.value,0.0) }
    @Test fun midPreservesMarketDataCurrency() { val value=success(MarketDataCalculationType.MID,candidate(currency="JPY")) as MarketDataCalculationValue.MidPrice; assertEquals("JPY",value.currency) }
    @Test fun spreadInvalidBidPreservesCalculatorFailure() { assertFailure(MarketDataCalculationType.SPREAD,candidate(bid=-1.0),MarketDataCalculationError.INVALID_BID) }
    @Test fun spreadInvalidAskPreservesCalculatorFailure() { assertFailure(MarketDataCalculationType.SPREAD,candidate(ask=0.0),MarketDataCalculationError.INVALID_ASK) }
    @Test fun spreadBidAboveAskPreservesCalculatorFailure() { assertFailure(MarketDataCalculationType.SPREAD,candidate(bid=11.0,ask=10.0),MarketDataCalculationError.BID_ABOVE_ASK) }
    @Test fun midCalculatorFailureIsPreserved() { val candidate=candidate(bid=11.0,ask=10.0); val direct=MarketDataCalculator.calculateMidPrice(11.0,10.0) as MarketDataCalculationResult.Failure; assertFailure(MarketDataCalculationType.MID,candidate,direct.error) }
    @Test fun emptyInputReturnsNoInputCandidates() { assertSame(KnockoutProductCandidateCalculationResult.NoInputCandidates,service.execute(request(emptyList(),MarketDataCalculationType.MID))) }
    @Test fun inputOrderIsPreserved() { val a=candidate("A",bid=9.0,ask=10.0); val b=candidate("B",bid=-1.0,ask=10.0); val c=candidate("C",bid=8.0,ask=10.0); val result=calculated(MarketDataCalculationType.SPREAD,listOf(a,b,c)); assertEquals(listOf(a,b,c),result.candidates.map { it.candidateWithSourceEvaluation }) }
    @Test fun successfulAndFailedCalculationsRemainTogether() { val success=candidate("A",bid=9.0,ask=10.0); val failure=candidate("B",bid=-1.0,ask=10.0); val result=calculated(MarketDataCalculationType.SPREAD,listOf(success,failure)); assertEquals(2,result.candidates.size); assertTrue(result.candidates[0].calculationOutcome is KnockoutProductCandidateCalculationOutcome.Success); assertTrue(result.candidates[1].calculationOutcome is KnockoutProductCandidateCalculationOutcome.Failure) }
    @Test fun candidateDuplicatesRemainDuplicated() { val candidate=candidate(); val result=calculated(MarketDataCalculationType.MID,listOf(candidate,candidate)); assertEquals(2,result.candidates.size); assertSame(candidate,result.candidates[0].candidateWithSourceEvaluation); assertSame(candidate,result.candidates[1].candidateWithSourceEvaluation) }
    @Test fun equalIsinsAreCalculatedAsSeparateEntries() { val first=candidate("DE000SYNTH01"); val second=candidate("DE000SYNTH01"); val result=calculated(MarketDataCalculationType.MID,listOf(first,second)); assertEquals(2,result.candidates.size); assertSame(first,result.candidates[0].candidateWithSourceEvaluation); assertSame(second,result.candidates[1].candidateWithSourceEvaluation) }
    @Test fun originalInstancesRequestAndInputListRemainUnchanged() { val finding=DataQualityFinding(DataQualityCategory.MISSING_REQUIRED_DATA,DataQualitySeverity.WARNING,DataQualityFindingCode.MARKET_DATA_MISSING_SOURCE_ID,DataQualityComponent.PRODUCT_MARKET_DATA); val assessment=DataQualityAssessment.warning(listOf(finding)); val availability=MarketDataCalculationAvailabilityResult.StructurallyUnavailable(listOf(MarketDataCalculationAvailabilityError.MISSING_BID)); val freshness=MarketDataFreshnessResult.NotFresh(listOf(MarketDataFreshnessError.STALE_ASK)); val source=MarketDataSourceResult.Blocked(MarketDataSourceError.SOURCE_NOT_CONFIGURED); val candidate=candidate(assessment=assessment,availability=availability,freshness=freshness,source=source); val input=mutableListOf(candidate,candidate); val original=input.toList(); val request=request(input,MarketDataCalculationType.MID); val preserved=calculated(request.calculationType,request.candidates).candidates.first().candidateWithSourceEvaluation; val freshnessCandidate=preserved.candidateWithFreshness; val availabilityCandidate=freshnessCandidate.candidateWithCalculationAvailability; val qualityCandidate=availabilityCandidate.candidateWithDataQuality; val marketCandidate=qualityCandidate.candidateWithMarketData; assertSame(input,request.candidates); assertEquals(original,input); assertEquals(MarketDataCalculationType.MID,request.calculationType); assertSame(candidate,preserved); assertSame(freshnessCandidate,preserved.candidateWithFreshness); assertSame(availabilityCandidate,freshnessCandidate.candidateWithCalculationAvailability); assertSame(qualityCandidate,availabilityCandidate.candidateWithDataQuality); assertSame(marketCandidate,qualityCandidate.candidateWithMarketData); assertSame(assessment,qualityCandidate.dataQualityAssessment); assertEquals(listOf(finding),assessment.findings); assertSame(availability,availabilityCandidate.availabilityResult); assertSame(freshness,freshnessCandidate.freshnessResult); assertSame(source,preserved.sourceResult) }
    @Test fun resultMatchesDirectCalculatorAndContainsNoLaterStageOutput() { val candidate=candidate(bid=9.0,ask=10.0); val directAbsolute=MarketDataCalculator.calculateAbsoluteSpread(9.0,10.0) as MarketDataCalculationResult.Success; val directRelative=MarketDataCalculator.calculateRelativeSpreadToAskPercent(9.0,10.0) as MarketDataCalculationResult.Success; val request=request(listOf(candidate),MarketDataCalculationType.SPREAD); val first=service.execute(request) as KnockoutProductCandidateCalculationResult.CandidatesWithCalculation; val second=service.execute(request) as KnockoutProductCandidateCalculationResult.CandidatesWithCalculation; val value=(first.candidates.single().calculationOutcome as KnockoutProductCandidateCalculationOutcome.Success).value as MarketDataCalculationValue.Spread; assertEquals(directAbsolute.value,value.absoluteSpread,0.0); assertEquals(directRelative.value,value.relativeSpreadToAskPercent,0.0); assertEquals(first,second); assertSame(candidate,first.candidates.single().candidateWithSourceEvaluation) }

    private fun success(type:MarketDataCalculationType,candidate:KnockoutProductCandidateWithSourceEvaluation):MarketDataCalculationValue { val outcome=calculated(type,listOf(candidate)).candidates.single().calculationOutcome; assertTrue(outcome is KnockoutProductCandidateCalculationOutcome.Success); return (outcome as KnockoutProductCandidateCalculationOutcome.Success).value }
    private fun assertFailure(type:MarketDataCalculationType,candidate:KnockoutProductCandidateWithSourceEvaluation,error:MarketDataCalculationError) { val outcome=calculated(type,listOf(candidate)).candidates.single().calculationOutcome; assertTrue(outcome is KnockoutProductCandidateCalculationOutcome.Failure); assertEquals(error,(outcome as KnockoutProductCandidateCalculationOutcome.Failure).error) }
    private fun calculated(type:MarketDataCalculationType,candidates:List<KnockoutProductCandidateWithSourceEvaluation>):KnockoutProductCandidateCalculationResult.CandidatesWithCalculation { val result=service.execute(request(candidates,type)); assertTrue(result is KnockoutProductCandidateCalculationResult.CandidatesWithCalculation); return result as KnockoutProductCandidateCalculationResult.CandidatesWithCalculation }
    private fun request(candidates:List<KnockoutProductCandidateWithSourceEvaluation>,type:MarketDataCalculationType)=KnockoutProductCandidateCalculationRequest(candidates,type)
    private fun candidate(isin:String="DE000SYNTH01",bid:Double?=9.0,ask:Double?=10.0,currency:String="EUR",assessment:DataQualityAssessment=DataQualityAssessment.passed(),availability:MarketDataCalculationAvailabilityResult=MarketDataCalculationAvailabilityResult.StructurallyAvailable,freshness:MarketDataFreshnessResult=MarketDataFreshnessResult.Fresh,source:MarketDataSourceResult=MarketDataSourceResult.Allowed):KnockoutProductCandidateWithSourceEvaluation { val specification=KnockoutProductSpecification(isin,"SYN001","issuer","underlying",TradeDirection.LONG,100.0,95.0,0.1,"EUR",currency); val snapshot=KnockoutProductSpecificationSnapshot(specification,"snapshot",1000L,900L); val marketData=KnockoutProductMarketData(isin,bid,ask,950L,950L,currency,"SYNTH_SOURCE"); val marketCandidate=KnockoutProductCandidateWithMarketData(snapshot,marketData); val qualityCandidate=KnockoutProductCandidateWithDataQuality(marketCandidate,assessment); val availabilityCandidate=KnockoutProductCandidateWithCalculationAvailability(qualityCandidate,availability); return KnockoutProductCandidateWithSourceEvaluation(KnockoutProductCandidateWithFreshness(availabilityCandidate,freshness),source) }
}
