package de.konavigator.app.application.productdiscovery

import de.konavigator.app.calculator.TradeCalculationError
import de.konavigator.app.calculator.TradeCalculationResult
import de.konavigator.app.domain.availability.MarketDataCalculationAvailabilityError
import de.konavigator.app.domain.availability.MarketDataCalculationAvailabilityResult
import de.konavigator.app.domain.calculator.MarketDataCalculationError
import de.konavigator.app.domain.currency.CurrencyCode
import de.konavigator.app.domain.currency.CurrencyCodeCreationResult
import de.konavigator.app.domain.currency.CurrencyConversion
import de.konavigator.app.domain.dataquality.DataQualityAssessment
import de.konavigator.app.domain.dataquality.DataQualityCategory
import de.konavigator.app.domain.dataquality.DataQualityComponent
import de.konavigator.app.domain.dataquality.DataQualityFinding
import de.konavigator.app.domain.dataquality.DataQualityFindingCode
import de.konavigator.app.domain.dataquality.DataQualitySeverity
import de.konavigator.app.domain.freshness.MarketDataFreshnessError
import de.konavigator.app.domain.freshness.MarketDataFreshnessResult
import de.konavigator.app.domain.model.KnockoutProductMarketData
import de.konavigator.app.domain.model.KnockoutProductSpecification
import de.konavigator.app.domain.model.KnockoutProductSpecificationSnapshot
import de.konavigator.app.domain.model.TradeDirection
import de.konavigator.app.domain.orchestration.MarketDataCalculationValue
import de.konavigator.app.domain.source.MarketDataSourceError
import de.konavigator.app.domain.source.MarketDataSourceResult
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertSame
import org.junit.Assert.assertTrue
import org.junit.Test

class KnockoutProductCandidateTargetLeverageGateTest {
    private val gate=KnockoutProductCandidateTargetLeverageGate()

    @Test fun validCandidateIsReleasedForBarrierComparison() { val candidate=candidate(validResult()); val result=validResult(listOf(candidate)); assertEquals(listOf(candidate),result.validCandidates); assertTrue(result.invalidCandidates.isEmpty()) }
    @Test fun invalidCandidateReturnsNoValidTargetLeveragePlanCandidates() { val trade=invalidResult(TradeCalculationError.INVALID_RATIO); val candidate=candidate(trade); val result=gate.filter(request(listOf(candidate))) as KnockoutProductCandidateTargetLeverageGateResult.NoValidTargetLeveragePlanCandidates; assertSame(candidate,result.invalidCandidates.single()); assertSame(trade,result.invalidCandidates.single().tradeCalculationResult) }
    @Test fun emptyInputReturnsNoInputCandidates() { assertSame(KnockoutProductCandidateTargetLeverageGateResult.NoInputCandidates,gate.filter(request(emptyList()))) }
    @Test fun validAndInvalidCandidatesArePartitioned() { val a=candidate(validResult()); val b=candidate(invalidResult(TradeCalculationError.INVALID_RATIO)); val c=candidate(validResult(),isin="C"); val result=validResult(listOf(a,b,c)); assertEquals(listOf(a,c),result.validCandidates); assertEquals(listOf(b),result.invalidCandidates); assertEquals(3,result.validCandidates.size+result.invalidCandidates.size); assertFalse(result.validCandidates.any { it===b }) }
    @Test fun allValidCandidatesProduceEmptyInvalidList() { val a=candidate(validResult()); val b=candidate(validResult(),isin="B"); val result=validResult(listOf(a,b)); assertEquals(listOf(a,b),result.validCandidates); assertTrue(result.invalidCandidates.isEmpty()) }
    @Test fun allInvalidCandidatesRemainInNoValidResult() { val a=candidate(invalidResult(TradeCalculationError.INVALID_RATIO)); val b=candidate(invalidResult(TradeCalculationError.INVALID_TARGET_LEVERAGE),isin="B"); val result=gate.filter(request(listOf(a,b))) as KnockoutProductCandidateTargetLeverageGateResult.NoValidTargetLeveragePlanCandidates; assertEquals(listOf(a,b),result.invalidCandidates) }
    @Test fun validCandidateOrderIsPreserved() { val a=candidate(validResult()); val b=candidate(invalidResult(TradeCalculationError.INVALID_RATIO)); val c=candidate(validResult(),isin="C"); assertEquals(listOf(a,c),validResult(listOf(a,b,c)).validCandidates) }
    @Test fun invalidCandidateOrderIsPreserved() { val a=candidate(invalidResult(TradeCalculationError.INVALID_RATIO)); val b=candidate(validResult(),isin="B"); val c=candidate(invalidResult(TradeCalculationError.INVALID_TARGET_LEVERAGE),isin="C"); assertEquals(listOf(a,c),validResult(listOf(a,b,c)).invalidCandidates) }
    @Test fun duplicateValidCandidateRemainsDuplicated() { val candidate=candidate(validResult()); val result=validResult(listOf(candidate,candidate)); assertEquals(2,result.validCandidates.size); assertSame(candidate,result.validCandidates[0]); assertSame(candidate,result.validCandidates[1]) }
    @Test fun duplicateInvalidCandidateRemainsDuplicated() { val candidate=candidate(invalidResult(TradeCalculationError.INVALID_RATIO)); val result=gate.filter(request(listOf(candidate,candidate))) as KnockoutProductCandidateTargetLeverageGateResult.NoValidTargetLeveragePlanCandidates; assertEquals(2,result.invalidCandidates.size); assertSame(candidate,result.invalidCandidates[0]); assertSame(candidate,result.invalidCandidates[1]) }
    @Test fun equalIsinsRemainSeparateCandidateEntries() { val a=candidate(validResult(),isin="DE000SYNTH01"); val b=candidate(invalidResult(TradeCalculationError.INVALID_RATIO),isin="DE000SYNTH01"); val result=validResult(listOf(a,b)); assertSame(a,result.validCandidates.single()); assertSame(b,result.invalidCandidates.single()) }
    @Test fun differentExactIsinSpellingsRemainSeparate() { val a=candidate(validResult(),isin="DE000SYNTH01"); val b=candidate(validResult(),isin="de000synth01"); val c=candidate(validResult(),isin=" DE000SYNTH01 "); assertEquals(listOf("DE000SYNTH01","de000synth01"," DE000SYNTH01 "),validResult(listOf(a,b,c)).validCandidates.map { isin(it) }) }
    @Test fun equalSourceIdsRemainSeparateCandidateEntries() { val a=candidate(validResult(),sourceId="SYNTH"); val b=candidate(validResult(),isin="B",sourceId="SYNTH"); val result=validResult(listOf(a,b)); assertEquals(2,result.validCandidates.size); assertSame(a,result.validCandidates[0]); assertSame(b,result.validCandidates[1]) }
    @Test fun differentProductsFromSameIssuerRemainSeparate() { val a=candidate(validResult(),isin="A",issuer="issuer"); val b=candidate(validResult(),isin="B",issuer="issuer"); assertEquals(listOf(a,b),validResult(listOf(a,b)).validCandidates) }
    @Test fun longAndShortPlansRemainSeparateEntries() { val long=candidate(validResult(),direction=TradeDirection.LONG); val short=candidate(validResult(),isin="B",direction=TradeDirection.SHORT); assertEquals(listOf(long,short),validResult(listOf(long,short)).validCandidates) }
    @Test fun resultIsNotLimitedToThreeCandidates() { val candidates=(1..4).map { candidate(validResult(),isin="S$it") }; assertEquals(candidates,validResult(candidates).validCandidates) }
    @Test fun candidateAndPreviousInstancesRemainUnchanged() { val trade=validResult(); val candidate=candidate(trade); val preserved=validResult(listOf(candidate)).validCandidates.single(); val input=preserved.input; val calculation=input.candidateWithCalculation; val source=calculation.candidateWithSourceEvaluation; val freshness=source.candidateWithFreshness; val availability=freshness.candidateWithCalculationAvailability; val quality=availability.candidateWithDataQuality; val market=quality.candidateWithMarketData; assertSame(candidate,preserved); assertSame(input,preserved.input); assertSame(calculation,input.candidateWithCalculation); assertSame(source,calculation.candidateWithSourceEvaluation); assertSame(freshness,source.candidateWithFreshness); assertSame(availability,freshness.candidateWithCalculationAvailability); assertSame(quality,availability.candidateWithDataQuality); assertSame(market,quality.candidateWithMarketData); assertSame(market.specificationSnapshot,market.specificationSnapshot); assertSame(market.specificationSnapshot.specification,market.specificationSnapshot.specification); assertSame(market.marketData,market.marketData); assertSame(input.currencyConversion,input.currencyConversion); assertSame(quality.dataQualityAssessment,quality.dataQualityAssessment); assertSame(availability.availabilityResult,availability.availabilityResult); assertSame(freshness.freshnessResult,freshness.freshnessResult); assertSame(source.sourceResult,source.sourceResult); assertSame(calculation.calculationOutcome,calculation.calculationOutcome); assertSame(trade,preserved.tradeCalculationResult) }
    @Test fun previousFindingsErrorsAndTradeResultFieldsRemainUnchanged() { val first=finding(DataQualityFindingCode.MARKET_DATA_MISSING_SOURCE_ID); val second=finding(DataQualityFindingCode.MARKET_DATA_MISSING_BID_TIMESTAMP); val assessment=DataQualityAssessment.warning(listOf(first,second)); val availability=MarketDataCalculationAvailabilityResult.StructurallyUnavailable(listOf(MarketDataCalculationAvailabilityError.MISSING_BID,MarketDataCalculationAvailabilityError.MISSING_ASK)); val freshness=MarketDataFreshnessResult.NotFresh(listOf(MarketDataFreshnessError.STALE_BID,MarketDataFreshnessError.STALE_ASK)); val source=MarketDataSourceResult.Blocked(MarketDataSourceError.SOURCE_NOT_CONFIGURED); val calculation=KnockoutProductCandidateCalculationOutcome.Failure(MarketDataCalculationError.INVALID_BID); val trade=invalidResult(TradeCalculationError.INVALID_RATIO); val candidate=candidate(trade,assessment=assessment,availability=availability,freshness=freshness,source=source,calculation=calculation); val preserved=(gate.filter(request(listOf(candidate))) as KnockoutProductCandidateTargetLeverageGateResult.NoValidTargetLeveragePlanCandidates).invalidCandidates.single(); val candidateAvailability=preserved.input.candidateWithCalculation.candidateWithSourceEvaluation.candidateWithFreshness.candidateWithCalculationAvailability; assertSame(assessment,candidateAvailability.candidateWithDataQuality.dataQualityAssessment); assertEquals(listOf(first,second),assessment.findings); assertSame(availability,candidateAvailability.availabilityResult); assertEquals(availability.errors,(candidateAvailability.availabilityResult as MarketDataCalculationAvailabilityResult.StructurallyUnavailable).errors); assertSame(freshness,preserved.input.candidateWithCalculation.candidateWithSourceEvaluation.candidateWithFreshness.freshnessResult); assertEquals(freshness.errors,(preserved.input.candidateWithCalculation.candidateWithSourceEvaluation.candidateWithFreshness.freshnessResult as MarketDataFreshnessResult.NotFresh).errors); assertSame(source,preserved.input.candidateWithCalculation.candidateWithSourceEvaluation.sourceResult); assertSame(calculation,preserved.input.candidateWithCalculation.calculationOutcome); assertSame(trade,preserved.tradeCalculationResult); assertEquals(trade, preserved.tradeCalculationResult) }
    @Test fun classificationUsesIsValidOnlyAndInputIsNotMutated() { val unusualValid=TradeCalculationResult(true,null,null,null,null,null,null,null,null,null,null,null,TradeCalculationError.INVALID_RATIO); val unusualInvalid=TradeCalculationResult(false,100.0,5.0,80.0,2.0,0.2,100.0,5.0,code("EUR"),code("EUR"),20.0,20.0,null); val a=candidate(unusualValid,sourceId="A"); val b=candidate(unusualInvalid,isin="B",sourceId="B"); val input=mutableListOf(a,b,a); val original=input.toList(); val request=request(input); val result=validResult(gate.filter(request)); assertEquals(listOf(a,a),result.validCandidates); assertEquals(listOf(b),result.invalidCandidates); assertSame(input,request.candidates); assertEquals(original,input); assertEquals(listOf("A","B","A"),input.map { sourceId(it) }) }
    @Test fun repeatedFilterCallsDoNotShareStateAndContainNoLaterStageOutput() { val valid=candidate(validResult()); val invalid=candidate(invalidResult(TradeCalculationError.INVALID_RATIO),isin="B"); val request=request(listOf(valid,invalid)); val first=gate.filter(request); val second=gate.filter(request); assertEquals(first,second); assertSame(valid,validResult(first).validCandidates.single()); assertSame(invalid,validResult(second).invalidCandidates.single()) }

    private fun validResult(candidates:List<KnockoutProductCandidateWithTargetLeveragePlan>)=validResult(gate.filter(request(candidates)))
    private fun validResult(result:KnockoutProductCandidateTargetLeverageGateResult):KnockoutProductCandidateTargetLeverageGateResult.ValidTargetLeveragePlanCandidates { assertTrue(result is KnockoutProductCandidateTargetLeverageGateResult.ValidTargetLeveragePlanCandidates); return result as KnockoutProductCandidateTargetLeverageGateResult.ValidTargetLeveragePlanCandidates }
    private fun request(candidates:List<KnockoutProductCandidateWithTargetLeveragePlan>)=KnockoutProductCandidateTargetLeverageGateRequest(candidates)
    private fun validResult()=TradeCalculationResult(true,100.0,5.0,80.0,2.0,0.2,100.0,5.0,code("EUR"),code("EUR"),20.0,20.0,null)
    private fun invalidResult(error:TradeCalculationError)=TradeCalculationResult(false,null,null,null,null,null,null,null,null,null,null,null,error)
    private fun code(value:String)=(CurrencyCode.create(value) as CurrencyCodeCreationResult.Success).currencyCode
    private fun finding(code:DataQualityFindingCode)=DataQualityFinding(DataQualityCategory.MISSING_REQUIRED_DATA,DataQualitySeverity.WARNING,code,DataQualityComponent.PRODUCT_MARKET_DATA)
    private fun isin(candidate:KnockoutProductCandidateWithTargetLeveragePlan)=candidate.input.candidateWithCalculation.candidateWithSourceEvaluation.candidateWithFreshness.candidateWithCalculationAvailability.candidateWithDataQuality.candidateWithMarketData.specificationSnapshot.specification.productIsin
    private fun sourceId(candidate:KnockoutProductCandidateWithTargetLeveragePlan)=candidate.input.candidateWithCalculation.candidateWithSourceEvaluation.candidateWithFreshness.candidateWithCalculationAvailability.candidateWithDataQuality.candidateWithMarketData.marketData.sourceId
    private fun candidate(trade:TradeCalculationResult,isin:String="DE000SYNTH01",issuer:String="issuer",sourceId:String="SYNTH_SOURCE",direction:TradeDirection=TradeDirection.LONG,assessment:DataQualityAssessment=DataQualityAssessment.passed(),availability:MarketDataCalculationAvailabilityResult=MarketDataCalculationAvailabilityResult.StructurallyAvailable,freshness:MarketDataFreshnessResult=MarketDataFreshnessResult.Fresh,source:MarketDataSourceResult=MarketDataSourceResult.Allowed,calculation:KnockoutProductCandidateCalculationOutcome=KnockoutProductCandidateCalculationOutcome.Success(MarketDataCalculationValue.MidPrice(1.0,"EUR"))):KnockoutProductCandidateWithTargetLeveragePlan { val specification=KnockoutProductSpecification(isin,"SYN001",issuer,"underlying",direction,100.0,95.0,0.1,"EUR","EUR"); val snapshot=KnockoutProductSpecificationSnapshot(specification,"snapshot",1000L,900L); val marketData=KnockoutProductMarketData(isin,1.0,1.2,950L,950L,"EUR",sourceId); val marketCandidate=KnockoutProductCandidateWithMarketData(snapshot,marketData); val qualityCandidate=KnockoutProductCandidateWithDataQuality(marketCandidate,assessment); val availabilityCandidate=KnockoutProductCandidateWithCalculationAvailability(qualityCandidate,availability); val sourceCandidate=KnockoutProductCandidateWithSourceEvaluation(KnockoutProductCandidateWithFreshness(availabilityCandidate,freshness),source); val calculationCandidate=KnockoutProductCandidateWithCalculation(sourceCandidate,calculation); val input=KnockoutProductCandidateTargetLeverageInput(calculationCandidate,CurrencyConversion.SameCurrency(code("EUR"))); return KnockoutProductCandidateWithTargetLeveragePlan(input,trade) }
}
