package de.konavigator.app.application.productdiscovery

import de.konavigator.app.domain.availability.MarketDataCalculationAvailabilityError
import de.konavigator.app.domain.availability.MarketDataCalculationAvailabilityResult
import de.konavigator.app.domain.calculator.MarketDataCalculationError
import de.konavigator.app.domain.dataquality.DataQualityAssessment
import de.konavigator.app.domain.dataquality.DataQualityCategory
import de.konavigator.app.domain.dataquality.DataQualityComponent
import de.konavigator.app.domain.dataquality.DataQualityFinding
import de.konavigator.app.domain.dataquality.DataQualityFindingCode
import de.konavigator.app.domain.dataquality.DataQualitySeverity
import de.konavigator.app.domain.freshness.MarketDataFreshnessError
import de.konavigator.app.domain.freshness.MarketDataFreshnessResult
import de.konavigator.app.domain.model.KnockoutProductMarketData
import de.konavigator.app.domain.model.KnockoutProductSpecification
import de.konavigator.app.domain.model.KnockoutProductSpecificationSnapshot
import de.konavigator.app.domain.model.TradeDirection
import de.konavigator.app.domain.orchestration.MarketDataCalculationValue
import de.konavigator.app.domain.source.MarketDataSourceError
import de.konavigator.app.domain.source.MarketDataSourceResult
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertSame
import org.junit.Assert.assertTrue
import org.junit.Test

class KnockoutProductCandidateCalculationGateTest {
    private val gate = KnockoutProductCandidateCalculationGate()

    @Test fun successfulCandidateIsReleasedForLaterEvaluation() { val c=candidate(); val r=successfulResult(listOf(c)); assertEquals(listOf(c),r.successfulCandidates); assertTrue(r.failedCandidates.isEmpty()) }
    @Test fun failedCandidateReturnsNoSuccessfulCalculationCandidates() { val outcome=failure(MarketDataCalculationError.INVALID_BID); val c=candidate(outcome=outcome); val r=gate.filter(request(listOf(c))) as KnockoutProductCandidateCalculationGateResult.NoSuccessfulCalculationCandidates; assertSame(c,r.failedCandidates.single()); assertSame(outcome,r.failedCandidates.single().calculationOutcome) }
    @Test fun emptyInputReturnsNoInputCandidates() { assertSame(KnockoutProductCandidateCalculationGateResult.NoInputCandidates,gate.filter(request(emptyList()))) }
    @Test fun successfulAndFailedCandidatesArePartitioned() { val a=candidate(); val b=candidate(outcome=failure(MarketDataCalculationError.INVALID_BID)); val c=candidate("C"); val r=successfulResult(listOf(a,b,c)); assertEquals(listOf(a,c),r.successfulCandidates); assertEquals(listOf(b),r.failedCandidates); assertEquals(3,r.successfulCandidates.size+r.failedCandidates.size); assertFalse(r.successfulCandidates.any { it===b }) }
    @Test fun allSuccessfulCandidatesProduceEmptyFailedList() { val a=candidate("A"); val b=candidate("B"); val r=successfulResult(listOf(a,b)); assertEquals(listOf(a,b),r.successfulCandidates); assertTrue(r.failedCandidates.isEmpty()) }
    @Test fun allFailedCandidatesRemainInNoSuccessfulResult() { val a=candidate("A",outcome=failure(MarketDataCalculationError.INVALID_BID)); val b=candidate("B",outcome=failure(MarketDataCalculationError.INVALID_ASK)); val r=gate.filter(request(listOf(a,b))) as KnockoutProductCandidateCalculationGateResult.NoSuccessfulCalculationCandidates; assertEquals(listOf(a,b),r.failedCandidates) }
    @Test fun successfulCandidateOrderIsPreserved() { val a=candidate("A"); val b=candidate("B",outcome=failure(MarketDataCalculationError.INVALID_BID)); val c=candidate("C"); assertEquals(listOf(a,c),successfulResult(listOf(a,b,c)).successfulCandidates) }
    @Test fun failedCandidateOrderIsPreserved() { val a=candidate("A",outcome=failure(MarketDataCalculationError.INVALID_BID)); val b=candidate("B"); val c=candidate("C",outcome=failure(MarketDataCalculationError.INVALID_ASK)); assertEquals(listOf(a,c),successfulResult(listOf(a,b,c)).failedCandidates) }
    @Test fun duplicateSuccessfulCandidateRemainsDuplicated() { val c=candidate(); val r=successfulResult(listOf(c,c)); assertEquals(2,r.successfulCandidates.size); assertSame(c,r.successfulCandidates[0]); assertSame(c,r.successfulCandidates[1]) }
    @Test fun duplicateFailedCandidateRemainsDuplicated() { val c=candidate(outcome=failure(MarketDataCalculationError.INVALID_BID)); val r=gate.filter(request(listOf(c,c))) as KnockoutProductCandidateCalculationGateResult.NoSuccessfulCalculationCandidates; assertEquals(2,r.failedCandidates.size); assertSame(c,r.failedCandidates[0]); assertSame(c,r.failedCandidates[1]) }
    @Test fun equalIsinsRemainSeparateCandidateEntries() { val a=candidate("DE000SYNTH01"); val b=candidate("DE000SYNTH01",outcome=failure(MarketDataCalculationError.INVALID_BID)); val r=successfulResult(listOf(a,b)); assertSame(a,r.successfulCandidates.single()); assertSame(b,r.failedCandidates.single()) }
    @Test fun differentExactIsinSpellingsRemainSeparate() { val a=candidate("DE000SYNTH01"); val b=candidate("de000synth01"); val c=candidate(" DE000SYNTH01 "); val r=successfulResult(listOf(a,b,c)); assertEquals(listOf("DE000SYNTH01","de000synth01"," DE000SYNTH01 "),r.successfulCandidates.map { isin(it) }) }
    @Test fun equalSourceIdsRemainSeparateCandidateEntries() { val a=candidate("A",sourceId="SYNTH_SOURCE"); val b=candidate("B",sourceId="SYNTH_SOURCE"); val r=successfulResult(listOf(a,b)); assertEquals(2,r.successfulCandidates.size); assertSame(a,r.successfulCandidates[0]); assertSame(b,r.successfulCandidates[1]) }
    @Test fun differentProductsFromSameIssuerRemainSeparate() { val a=candidate("A",issuer="issuer"); val b=candidate("B",issuer="issuer"); assertEquals(listOf(a,b),successfulResult(listOf(a,b)).successfulCandidates) }
    @Test fun differentCalculationValueTypesRemainSeparate() { val purchase=candidate(outcome=success(MarketDataCalculationValue.PurchasePrice(1.0,"EUR"))); val sale=candidate("B",outcome=success(MarketDataCalculationValue.SalePrice(1.0,"EUR"))); val spread=candidate("C",outcome=success(MarketDataCalculationValue.Spread(1.0,10.0,"EUR"))); val mid=candidate("D",outcome=success(MarketDataCalculationValue.MidPrice(1.0,"EUR"))); assertEquals(listOf(purchase,sale,spread,mid),successfulResult(listOf(purchase,sale,spread,mid)).successfulCandidates) }
    @Test fun resultIsNotLimitedToThreeCandidates() { val candidates=(1..4).map { candidate("S$it") }; assertEquals(candidates,successfulResult(candidates).successfulCandidates) }
    @Test fun candidateAndPreviousInstancesRemainUnchanged() { val value=MarketDataCalculationValue.PurchasePrice(1.0,"EUR"); val outcome=success(value); val candidate=candidate(outcome=outcome); val preserved=successfulResult(listOf(candidate)).successfulCandidates.single(); val source=preserved.candidateWithSourceEvaluation; val freshness=source.candidateWithFreshness; val availability=freshness.candidateWithCalculationAvailability; val quality=availability.candidateWithDataQuality; val market=quality.candidateWithMarketData; assertSame(candidate,preserved); assertSame(source,preserved.candidateWithSourceEvaluation); assertSame(freshness,source.candidateWithFreshness); assertSame(availability,freshness.candidateWithCalculationAvailability); assertSame(quality,availability.candidateWithDataQuality); assertSame(market,quality.candidateWithMarketData); assertSame(market.specificationSnapshot,quality.candidateWithMarketData.specificationSnapshot); assertSame(market.specificationSnapshot.specification,market.specificationSnapshot.specification); assertSame(market.marketData,market.marketData); assertSame(quality.dataQualityAssessment,quality.dataQualityAssessment); assertSame(availability.availabilityResult,availability.availabilityResult); assertSame(freshness.freshnessResult,freshness.freshnessResult); assertSame(source.sourceResult,source.sourceResult); assertSame(outcome,preserved.calculationOutcome); assertSame(value,(preserved.calculationOutcome as KnockoutProductCandidateCalculationOutcome.Success).value) }
    @Test fun previousFindingsErrorsAndResultsRemainUnchanged() { val one=finding(DataQualityFindingCode.MARKET_DATA_MISSING_SOURCE_ID); val two=finding(DataQualityFindingCode.MARKET_DATA_MISSING_BID_TIMESTAMP); val assessment=DataQualityAssessment.warning(listOf(one,two)); val availability=MarketDataCalculationAvailabilityResult.StructurallyUnavailable(listOf(MarketDataCalculationAvailabilityError.MISSING_BID,MarketDataCalculationAvailabilityError.MISSING_ASK)); val freshness=MarketDataFreshnessResult.NotFresh(listOf(MarketDataFreshnessError.STALE_BID,MarketDataFreshnessError.STALE_ASK)); val source=MarketDataSourceResult.Blocked(MarketDataSourceError.SOURCE_NOT_CONFIGURED); val outcome=failure(MarketDataCalculationError.INVALID_BID); val candidate=candidate(assessment=assessment,availability=availability,freshness=freshness,source=source,outcome=outcome); val preserved=(gate.filter(request(listOf(candidate))) as KnockoutProductCandidateCalculationGateResult.NoSuccessfulCalculationCandidates).failedCandidates.single(); val resultAvailability=preserved.candidateWithSourceEvaluation.candidateWithFreshness.candidateWithCalculationAvailability; assertSame(assessment,resultAvailability.candidateWithDataQuality.dataQualityAssessment); assertEquals(listOf(one,two),assessment.findings); assertSame(availability,resultAvailability.availabilityResult); assertEquals(availability.errors,(resultAvailability.availabilityResult as MarketDataCalculationAvailabilityResult.StructurallyUnavailable).errors); assertSame(freshness,preserved.candidateWithSourceEvaluation.candidateWithFreshness.freshnessResult); assertEquals(freshness.errors,(preserved.candidateWithSourceEvaluation.candidateWithFreshness.freshnessResult as MarketDataFreshnessResult.NotFresh).errors); assertSame(source,preserved.candidateWithSourceEvaluation.sourceResult); assertSame(outcome,preserved.calculationOutcome) }
    @Test fun allCalculatorErrorsRemainExactAndInputIsNotMutated() { val invalidBid=failure(MarketDataCalculationError.INVALID_BID); val invalidAsk=failure(MarketDataCalculationError.INVALID_ASK); val crossed=failure(MarketDataCalculationError.BID_ABOVE_ASK); val a=candidate("A",sourceId="A",outcome=invalidBid); val b=candidate("B",sourceId="B",outcome=invalidAsk); val c=candidate("C",sourceId="C",outcome=crossed); val input=mutableListOf(a,b,c,a); val original=input.toList(); val request=request(input); val result=gate.filter(request) as KnockoutProductCandidateCalculationGateResult.NoSuccessfulCalculationCandidates; assertEquals(listOf(invalidBid,invalidAsk,crossed,invalidBid),result.failedCandidates.map { it.calculationOutcome }); assertSame(input,request.candidates); assertEquals(original,input); assertEquals(listOf("A","B","C","A"),input.map { sourceId(it) }) }
    @Test fun repeatedFilterCallsDoNotShareStateAndContainNoLaterStageOutput() { val a=candidate("A"); val b=candidate("B",outcome=failure(MarketDataCalculationError.INVALID_BID)); val request=request(listOf(a,b)); val first=gate.filter(request); val second=gate.filter(request); assertEquals(first,second); assertSame(a,successfulResult(first).successfulCandidates.single()); assertSame(b,successfulResult(second).failedCandidates.single()) }

    private fun successfulResult(candidates:List<KnockoutProductCandidateWithCalculation>)=successfulResult(gate.filter(request(candidates)))
    private fun successfulResult(result:KnockoutProductCandidateCalculationGateResult):KnockoutProductCandidateCalculationGateResult.SuccessfulCalculationCandidates { assertTrue(result is KnockoutProductCandidateCalculationGateResult.SuccessfulCalculationCandidates); return result as KnockoutProductCandidateCalculationGateResult.SuccessfulCalculationCandidates }
    private fun request(candidates:List<KnockoutProductCandidateWithCalculation>)=KnockoutProductCandidateCalculationGateRequest(candidates)
    private fun success(value:MarketDataCalculationValue)=KnockoutProductCandidateCalculationOutcome.Success(value)
    private fun failure(error:MarketDataCalculationError)=KnockoutProductCandidateCalculationOutcome.Failure(error)
    private fun isin(candidate:KnockoutProductCandidateWithCalculation)=candidate.candidateWithSourceEvaluation.candidateWithFreshness.candidateWithCalculationAvailability.candidateWithDataQuality.candidateWithMarketData.specificationSnapshot.specification.productIsin
    private fun sourceId(candidate:KnockoutProductCandidateWithCalculation)=candidate.candidateWithSourceEvaluation.candidateWithFreshness.candidateWithCalculationAvailability.candidateWithDataQuality.candidateWithMarketData.marketData.sourceId
    private fun finding(code:DataQualityFindingCode)=DataQualityFinding(DataQualityCategory.MISSING_REQUIRED_DATA,DataQualitySeverity.WARNING,code,DataQualityComponent.PRODUCT_MARKET_DATA)
    private fun candidate(isin:String="DE000SYNTH01",issuer:String="issuer",sourceId:String="SYNTH_SOURCE",assessment:DataQualityAssessment=DataQualityAssessment.passed(),availability:MarketDataCalculationAvailabilityResult=MarketDataCalculationAvailabilityResult.StructurallyAvailable,freshness:MarketDataFreshnessResult=MarketDataFreshnessResult.Fresh,source:MarketDataSourceResult=MarketDataSourceResult.Allowed,outcome:KnockoutProductCandidateCalculationOutcome=success(MarketDataCalculationValue.MidPrice(1.0,"EUR"))):KnockoutProductCandidateWithCalculation { val specification=KnockoutProductSpecification(isin,"SYN001",issuer,"underlying",TradeDirection.LONG,100.0,95.0,0.1,"EUR","EUR"); val snapshot=KnockoutProductSpecificationSnapshot(specification,"snapshot",1000L,900L); val marketData=KnockoutProductMarketData(isin,1.0,1.2,950L,950L,"EUR",sourceId); val marketCandidate=KnockoutProductCandidateWithMarketData(snapshot,marketData); val qualityCandidate=KnockoutProductCandidateWithDataQuality(marketCandidate,assessment); val availabilityCandidate=KnockoutProductCandidateWithCalculationAvailability(qualityCandidate,availability); val sourceCandidate=KnockoutProductCandidateWithSourceEvaluation(KnockoutProductCandidateWithFreshness(availabilityCandidate,freshness),source); return KnockoutProductCandidateWithCalculation(sourceCandidate,outcome) }
}
